clear;clc;close all

load_path

% load nominal spring
spring = nominal_spring();

% generate random samples
rng('default'); % same random seed for reproductability
N_mc = 3e4; % number of MCS samples
uncertainty = .05;
X_1 = unifrnd( (1-uncertainty)*spring.d_i   , (1+uncertainty)*spring.d_i,    N_mc, 1);
X_2 = unifrnd( (1-uncertainty)*spring.d_w   , (1+uncertainty)*spring.d_w,    N_mc, 1);
X_3 = unifrnd( (1-uncertainty)*spring.L_free, (1+uncertainty)*spring.L_free, N_mc, 1);
X_4 = unifrnd( (1-uncertainty)*spring.N_t   , (1+uncertainty)*spring.N_t,    N_mc, 1);
X_5 = unifrnd( (1-uncertainty)*spring.nu    , (1+uncertainty)*spring.nu,     N_mc, 1);

% pack samples
spring_MCS.d_i    = X_1;
spring_MCS.d_w    = X_2;
spring_MCS.L_free = X_3;
spring_MCS.N_t    = X_4;
spring_MCS.nu     = X_5;
spring_MCS.end_condition = 'open';

% convert parameters
spring_MCS = Convert_Build_Params_vectorize(spring_MCS);

L_hat = 0.025;
delta = spring_MCS.L_free - L_hat;

theta = compute_theta_vectorize(spring_MCS,delta);

% get a theta from nominal values
spring_nominal = Convert_Build_Params_vectorize(spring);
delta_nominal = spring_nominal.L_free - L_hat;
theta_nominal = compute_theta_vectorize(spring_nominal,delta_nominal);

dis_idx = linspace(min(theta),max(theta),11);
[group_idx] = discretize(theta,dis_idx,dis_idx(1:end-1));

fig_surf = figure();
fig_surf.Position = [100 100 1600 500];
subplot(141);hold on;
f1=gscatter(X_4,X_1*1e3,group_idx,[],[],[],'off');
xlabel('$N_t$','fontsize',20,'interpreter','latex');
ylabel('$d_i~$(mm)','fontsize',20,'interpreter','latex');
set(gca           ,             ...
    'Box'         , 'on'      , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.02 .02] , ...
    'ticklabelinterpreter','latex' , ...
    'XMinorTick'  , 'off'     , ...
    'YMinorTick'  , 'off'     , ...
    'YGrid'       , 'on'     , ...
    'XGrid'       , 'on'     , ...
    'XColor'      , 'k'       , ...
    'YColor'      , 'k'       , ...
    'FontSize'    , 20        , ...
    'LineWidth'   , 1         );
axis square tight

subplot(142);hold on;
gscatter(X_4,X_2*1e3,group_idx,[],[],[],'off');
xlabel('$N_t$','fontsize',20,'interpreter','latex');
ylabel('$d_w~$(mm)','fontsize',20,'interpreter','latex');
set(gca           ,             ...
    'Box'         , 'on'      , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.02 .02] , ...
    'ticklabelinterpreter','latex' , ...
    'XMinorTick'  , 'off'     , ...
    'YMinorTick'  , 'off'     , ...
    'YGrid'       , 'on'     , ...
    'XGrid'       , 'on'     , ...
    'XColor'      , 'k'       , ...
    'YColor'      , 'k'       , ...
    'FontSize'    , 20        , ...
    'LineWidth'   , 1         );
axis square tight

subplot(143);hold on;
gscatter(X_4,X_3,group_idx,[],[],[],'off');
xlabel('$N_t$','fontsize',20,'interpreter','latex');
ylabel('$L_f~$(mm)','fontsize',20,'interpreter','latex');
set(gca           ,             ...
    'Box'         , 'on'      , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.02 .02] , ...
    'ticklabelinterpreter','latex' , ...
    'XMinorTick'  , 'off'     , ...
    'YMinorTick'  , 'off'     , ...
    'YGrid'       , 'on'     , ...
    'XGrid'       , 'on'     , ...
    'XColor'      , 'k'       , ...
    'YColor'      , 'k'       , ...
    'FontSize'    , 20        , ...
    'LineWidth'   , 1         );
axis square tight

subplot(144);hold on;
f1=gscatter(X_4,X_5,group_idx,[],[],[],'off');
% for k = 1:length(f1)
%     f1(k).MarkerSize = 9;
%     if k == 1
%         leg{k} = [num2str(dis_idx(k),'%.1f') '$\leq\theta \leq$' num2str(dis_idx(k+1),'%.1f')];
%     else
%     leg{k} = [num2str(dis_idx(k),'%.1f') '$<\theta \leq$' num2str(dis_idx(k+1),'%.1f')];
%     end
% end
% legend(leg)
% set(legend,'location','eastoutside','interpreter','latex','fontsize',15);
xlabel('$N_t$','fontsize',20,'interpreter','latex');
ylabel('$\nu$','fontsize',20,'interpreter','latex');
set(gca           ,             ...
    'Box'         , 'on'      , ...
    'TickDir'     , 'in'      , ...
    'TickLength'  , [.02 .02] , ...
    'ticklabelinterpreter','latex' , ...
    'XMinorTick'  , 'off'     , ...
    'YMinorTick'  , 'off'     , ...
    'YGrid'       , 'on'     , ...
    'XGrid'       , 'on'     , ...
    'XColor'      , 'k'       , ...
    'YColor'      , 'k'       , ...
    'FontSize'    , 20        , ...
    'LineWidth'   , 1         );
axis square tight





set(gcf,'PaperPositionMode','auto')
% print(['figures/surface_d_w_vs_parameters.fig'],'-deps','-r0','-painters')
savefig(['figures/surface_N_t_vs_parameters.fig'])

